#!/usr/bin/env python3
"""extract_features.py — interactive, wandb-tracked feature extraction for EmoVecLLM.

A head-less CLI port of ``notebooks/04_activation_extraction.ipynb`` for running
the activation-extraction stage on a remote GPU server, after the dataset has
been generated by ``generate_dataset.py`` (nb03). It runs each story through a
**target model**, reads the residual stream, and writes the same three artefacts
nb04 produces, keyed by ``{spec_hash}/{target_model}``:

- ``segment_features.npz``     — pooled (n_seg, n_layers, d) features + labels.
- ``emotion_vectors.npz``      — difference-of-means emotion directions + clusters.
- ``cumulative_timeseries.npz``— per-step (token×layer×d) residual timeseries.

Like the generator it: **asks** for the target model + method/runtime params
(CLI flag > ``EMOVEC_*`` env > prompt > default), **logs** every decision to a
run log + ``run_config.json``, and **tracks** per-segment progress + the final
``emotion_vectors.npz`` artefact to Weights & Biases. It reuses the shared
RunLogger / Resolver / Wandb infra from ``generate_dataset.py``.

Target model ≠ generator: nb03's *generator* wrote the stories; the *target*
(``--target-model`` / ``EMOVEC_TARGET_MODEL``, default ``gpt2``) is the model
whose emotion representation we extract.

Examples
--------
    python scripts/extract_features.py                      # interactive
    python scripts/extract_features.py --non-interactive \
        --target-model EleutherAI/pythia-1.4b --demo 0
    python scripts/extract_features.py --non-interactive --target-model gpt2 \
        --max-timeseries 20 --no-wandb                      # quick check
"""
from __future__ import annotations

import argparse
import json
import os
import re
import time
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np

# Shared infra lives in the sibling generation CLI (both tracked in scripts/).
from generate_dataset import (
    RunLogger, Resolver, Wandb, safe_name, resolve_work_dir,
    resolve_precision, PRECISION_CHOICES,
)

TARGET_MENU = [
    ("gpt2",                              "tiny — dev/demo default, runs anywhere"),
    ("EleutherAI/pythia-1.4b",            "small, clean — first real target"),
    ("Qwen/Qwen2.5-7B-Instruct",          "7B, Apache; 4-bit fits 24 GB"),
    ("meta-llama/Llama-3.1-8B-Instruct",  "8B, gated — needs HF_TOKEN"),
    ("mistralai/Mistral-7B-Instruct-v0.3", "7B cross-family check"),
]
BASELINE_CHOICES = ["auto", "neutral_mean", "project_pcs", "global_mean", "none"]


# ════════════════════════════════════════════════════════════════════════════
# Numeric core — ported verbatim from nb04 §4 (pure NumPy, backend-free)
# ════════════════════════════════════════════════════════════════════════════
def pool_segment(resid, pool="mean"):
    """resid (n_layers, seq, d) -> (n_layers, d)."""
    if pool == "last":
        return resid[:, -1, :].astype(np.float32)
    return resid.mean(axis=1).astype(np.float32)


def _unit(v, axis=-1, eps=1e-12):
    return v / (np.linalg.norm(v, axis=axis, keepdims=True) + eps)


def project_out_pcs(X, basis):
    """Remove the span of `basis` (k, d) rows from each row of X (n, d)."""
    if basis is None or len(basis) == 0:
        return X
    B = _unit(np.asarray(basis, dtype=np.float64), axis=1)
    Q = []
    for b in B:                                   # Gram-Schmidt (few components)
        for q in Q:
            b = b - (b @ q) * q
        n = np.linalg.norm(b)
        if n > 1e-9:
            Q.append(b / n)
    if not Q:
        return X
    Q = np.stack(Q, axis=0)
    return (X - (X @ Q.T) @ Q).astype(np.float32)


def cosine_sim_matrix(X):
    Xn = _unit(np.asarray(X, dtype=np.float64), axis=1)
    return (Xn @ Xn.T).astype(np.float32)


def build_emotion_vectors(class_means, neutral_mean, global_mean, mode, neutral_pcs=None):
    """class_means: dict[emotion] -> (n_layers, d). Returns (emotions, vectors)."""
    emotions = sorted(class_means)
    M = np.stack([class_means[e] for e in emotions], axis=0)   # (E, n_layers, d)
    if mode == "none":
        V = M
    elif mode == "global_mean":
        V = M - global_mean[None]
    else:   # neutral_mean / project_pcs both centre on neutral first
        base = neutral_mean if neutral_mean is not None else global_mean
        V = M - base[None]
        if mode == "project_pcs" and neutral_pcs is not None:
            V = np.stack([project_out_pcs(V[:, L, :], neutral_pcs[L])
                          for L in range(V.shape[1])], axis=1)
    return emotions, V.astype(np.float32)


def resolve_layer(spec, n_layers):
    return n_layers // 2 if str(spec) == "mid" else int(spec)


def resolve_layer_set(spec, n_layers, must_include):
    spec = str(spec)
    if spec == "all":
        idx = list(range(n_layers))
    elif spec == "mid":
        idx = [n_layers // 2]
    elif spec.lstrip("-").isdigit():                       # N evenly-spaced layers
        k = min(int(spec), n_layers)
        idx = sorted(set(np.linspace(0, n_layers - 1, k).round().astype(int).tolist()))
    else:                                                  # explicit csv of indices
        idx = [int(x) for x in spec.split(",")]
    return sorted(set(idx) | {must_include})


# ════════════════════════════════════════════════════════════════════════════
# Stories discovery (mirrors nb04 §2)
# ════════════════════════════════════════════════════════════════════════════
def discover_stories(data_dir: Path, explicit: str, logger: RunLogger) -> Path:
    if explicit:
        p = Path(explicit).expanduser()
        if not p.exists():
            raise SystemExit(f"EMOVEC_STORIES_PATH / --stories-path not found: {p}")
        return p
    candidates = sorted((data_dir / "stories").rglob("stories.jsonl"))
    if not candidates:
        raise SystemExit(
            f"no stories.jsonl under {data_dir/'stories'} — run generate_dataset.py "
            f"first, or pass --stories-path.")

    def _nlines(p):
        try:
            return sum(1 for _ in p.open())
        except Exception:
            return 0
    best = max(candidates, key=_nlines)
    if len(candidates) > 1:
        logger.log(f"found {len(candidates)} stories.jsonl; using the largest: {best}")
    return best


def flatten_items(records, min_tokens, max_seg_per_emotion):
    items = []
    for r in records:
        segs = r.get("segments") or ([r["raw"]] if r.get("raw") else [])
        for si, seg in enumerate(segs):
            seg = (seg or "").strip()
            if len(seg.split()) < min_tokens:
                continue
            items.append({"text": seg, "emotion": r.get("emotion"), "kind": r.get("kind"),
                          "job_id": r.get("job_id"), "topic": r.get("topic"), "seg_idx": si})
    if max_seg_per_emotion:
        per, capped = defaultdict(int), []
        for it in items:
            if it["kind"] == "emotion_story":
                if per[it["emotion"]] >= max_seg_per_emotion:
                    continue
                per[it["emotion"]] += 1
            capped.append(it)
        items = capped
    return items


# ════════════════════════════════════════════════════════════════════════════
# Target model loader (mirrors nb04 §3) → returns extract_resid(text)
# ════════════════════════════════════════════════════════════════════════════
def load_target(target, backend, precision, device_map, device, vram, max_tokens, logger):
    import torch
    tl_model = hf_model = hf_tok = None
    used = backend

    if backend in ("tlens", "auto"):
        try:
            from transformer_lens import HookedTransformer
            tl_model = HookedTransformer.from_pretrained(target, device=device)
            tl_model.eval()
            used = "tlens"
        except Exception as e:
            if backend == "tlens":
                raise
            logger.log(f"tlens unavailable for {target} ({type(e).__name__}); using hf.")
            used = "hf"

    if used != "tlens":
        from transformers import AutoModelForCausalLM, AutoTokenizer
        try:
            from transformers import BitsAndBytesConfig
        except Exception:
            BitsAndBytesConfig = None
        prec = resolve_precision(precision, device, vram)
        hf_token = os.environ.get("HF_TOKEN")
        hf_tok = AutoTokenizer.from_pretrained(target, trust_remote_code=True, token=hf_token)
        kw = dict(trust_remote_code=True, token=hf_token, output_hidden_states=True)
        if device == "cpu":
            kw.update(torch_dtype=torch.float32)
        elif prec in ("4bit", "8bit") and BitsAndBytesConfig is not None:
            kw.update(quantization_config=BitsAndBytesConfig(
                load_in_4bit=(prec == "4bit"), load_in_8bit=(prec == "8bit"),
                bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type="nf4",
                bnb_4bit_use_double_quant=True), device_map=device_map)
        else:
            dtype = (torch.bfloat16 if prec == "bf16" and torch.cuda.is_bf16_supported()
                     else torch.float16)
            kw.update(torch_dtype=dtype, device_map=device_map)
        logger.log(f"loading target {target} (backend=hf, precision={prec}) …")
        hf_model = AutoModelForCausalLM.from_pretrained(target, **kw)
        hf_model.eval()
        used = "hf"

    @torch.no_grad()
    def extract_resid(text):
        """Return (resid (n_layers, seq, d) float32, tokens list[str])."""
        if used == "tlens":
            toks = tl_model.to_tokens(text, prepend_bos=True)[:, :max_tokens]
            _, cache = tl_model.run_with_cache(toks, remove_batch_dim=True)
            n_layers = tl_model.cfg.n_layers
            resid = np.stack([cache[f"blocks.{i}.hook_resid_post"].cpu().float().numpy()
                              for i in range(n_layers)], axis=0)
            return resid.astype(np.float32), list(tl_model.to_str_tokens(toks))
        enc = hf_tok(text, return_tensors="pt", truncation=True, max_length=max_tokens)
        dev = hf_model.get_input_embeddings().weight.device
        enc = {k: v.to(dev) for k, v in enc.items()}
        hs = hf_model(**enc).hidden_states               # tuple len n_layers+1
        resid = np.stack([h[0].cpu().float().numpy() for h in hs[1:]], axis=0)  # drop embeds
        toks = hf_tok.convert_ids_to_tokens(enc["input_ids"][0].tolist())
        return resid.astype(np.float32), toks

    @torch.no_grad()
    def refeed_features(text, layer_idx):
        """Literal prefix re-feed: row t = last-token residual after reading tokens[:t+1]."""
        if used == "tlens":
            ids = tl_model.to_tokens(text, prepend_bos=True)[0, :max_tokens]
            toks = tl_model.to_str_tokens(ids)
        else:
            ids = hf_tok(text, truncation=True, max_length=max_tokens,
                         return_tensors="pt")["input_ids"][0]
            toks = hf_tok.convert_ids_to_tokens(ids.tolist())
        rows = []
        for t in range(1, len(ids) + 1):
            sub = ids[:t]
            if used == "tlens":
                _, c = tl_model.run_with_cache(sub.unsqueeze(0), remove_batch_dim=True)
                rows.append(np.stack([c[f"blocks.{L}.hook_resid_post"][-1].cpu().float().numpy()
                                      for L in layer_idx]))
            else:
                dev = hf_model.get_input_embeddings().weight.device
                hs = hf_model(input_ids=sub.unsqueeze(0).to(dev)).hidden_states
                rows.append(np.stack([hs[L + 1][0, -1].cpu().float().numpy() for L in layer_idx]))
        return np.stack(rows, axis=0), toks

    logger.log(f"target loaded (backend={used})")
    return extract_resid, refeed_features, used


# ════════════════════════════════════════════════════════════════════════════
# CLI
# ════════════════════════════════════════════════════════════════════════════
def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="Interactive, wandb-tracked EmoVecLLM feature extraction (nb04).",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--non-interactive", action="store_true")
    p.add_argument("--work-dir")
    p.add_argument("--stories-path", help="explicit stories.jsonl (skip auto-discovery)")
    p.add_argument("--target-model")
    p.add_argument("--backend", choices=["hf", "tlens", "auto"])
    p.add_argument("--precision", choices=PRECISION_CHOICES)
    p.add_argument("--device-map")
    p.add_argument("--demo", type=int, choices=[0, 1])
    p.add_argument("--pool", choices=["mean", "last"])
    p.add_argument("--skip-first", dest="skip_first", action="store_const", const=True, default=None)
    p.add_argument("--no-skip-first", dest="skip_first", action="store_const", const=False)
    p.add_argument("--cluster-layer")
    p.add_argument("--cum-layer")
    p.add_argument("--cum-layers")
    p.add_argument("--cum-method", choices=["singlepass", "refeed"])
    p.add_argument("--k", type=int)
    p.add_argument("--baseline", choices=BASELINE_CHOICES)
    p.add_argument("--baseline-pcs", type=int)
    p.add_argument("--min-tokens", type=int)
    p.add_argument("--max-tokens", type=int)
    p.add_argument("--max-seg-per-emotion", type=int)
    p.add_argument("--max-timeseries", type=int)
    p.add_argument("--wandb-project", default=None)
    p.add_argument("--wandb-entity", default=None)
    p.add_argument("--wandb-run-name", default=None)
    p.add_argument("--wandb-mode", choices=["online", "offline", "disabled"], default=None)
    p.add_argument("--no-wandb", action="store_true")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    work_dir = resolve_work_dir(args)
    data_dir = work_dir / "data" / "processed"

    stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    logger = RunLogger(work_dir / "logs" / f"extract_features_{stamp}.log")
    logger.log("=" * 72)
    logger.log(f"EmoVecLLM feature extraction — {stamp}")
    logger.log(f"work_dir : {work_dir}")
    logger.log("=" * 72)
    resolver = Resolver(args, logger)

    # ── Decisions ───────────────────────────────────────────────────────────
    logger.log("\n── parameters ──")
    target = resolver.pick("target_model", args.target_model, "EMOVEC_TARGET_MODEL",
                           TARGET_MENU, "gpt2")
    backend = resolver.choice("backend", args.backend, "EMOVEC_BACKEND",
                              ["hf", "tlens", "auto"], "hf")
    precision = resolver.choice("precision", args.precision, "EMOVEC_PRECISION",
                                PRECISION_CHOICES, "auto")
    device_map = resolver.value("device_map", args.device_map, "EMOVEC_DEVICE_MAP", "auto")
    demo = resolver.flag("demo", (None if args.demo is None else bool(args.demo)),
                         "EMOVEC_DEMO", True)
    pool = resolver.choice("pool", args.pool, "EMOVEC_POOL", ["mean", "last"], "mean")
    skip_first = resolver.flag("skip_first", args.skip_first, "EMOVEC_SKIP_FIRST", True)
    cluster_layer = resolver.value("cluster_layer", args.cluster_layer,
                                   "EMOVEC_CLUSTER_LAYER", "mid")
    cum_layer = resolver.value("cum_layer", args.cum_layer, "EMOVEC_CUM_LAYER", "mid")
    cum_layers = resolver.value("cum_layers", args.cum_layers, "EMOVEC_CUM_LAYERS", "8")
    cum_method = resolver.choice("cum_method", args.cum_method, "EMOVEC_CUM_METHOD",
                                 ["singlepass", "refeed"], "singlepass")
    k = int(resolver.value("k", args.k, "EMOVEC_K", 10))
    baseline = resolver.choice("baseline", args.baseline, "EMOVEC_BASELINE",
                               BASELINE_CHOICES, "auto")
    baseline_pcs = int(resolver.value("baseline_pcs", args.baseline_pcs,
                                      "EMOVEC_BASELINE_PCS", 5))
    min_tokens = int(resolver.value("min_tokens", args.min_tokens, "EMOVEC_MIN_TOKENS", 16))
    max_tokens = int(resolver.value("max_tokens", args.max_tokens, "EMOVEC_MAX_TOKENS", 256))
    max_seg = int(resolver.value("max_seg_per_emotion", args.max_seg_per_emotion,
                                 "EMOVEC_MAX_SEG_PER_EMOTION", 8 if demo else 0))
    max_ts = int(resolver.value("max_timeseries", args.max_timeseries,
                                "EMOVEC_MAX_TIMESERIES", 60 if demo else 400))

    # ── Discover + flatten stories ──────────────────────────────────────────
    stories_file = discover_stories(data_dir, args.stories_path or
                                    os.environ.get("EMOVEC_STORIES_PATH", ""), logger)
    records = [json.loads(l) for l in stories_file.read_text().splitlines() if l.strip()]
    if not records:
        raise SystemExit(f"no records in {stories_file}")
    spec_hash = records[0].get("spec_hash", "nospec")
    generator_used = records[0].get("generator_model", "?")
    items = flatten_items(records, min_tokens, max_seg)
    emo_items = [it for it in items if it["kind"] == "emotion_story"]
    neutral_idx = [i for i, it in enumerate(items)
                   if it["kind"] in ("neutral_dialogue", "neutral_story")]
    emo_dist = Counter(it["emotion"] for it in emo_items)

    logger.log(f"\nstories  : {stories_file}")
    logger.log(f"spec_hash: {spec_hash}  (generated by {generator_used})")
    logger.log(f"segments : {len(items)} usable  "
               f"(emotion={len(emo_items)}, neutral={len(neutral_idx)})")
    logger.log(f"emotions : {len(emo_dist)} covered  "
               f"(min/emotion={min(emo_dist.values()) if emo_dist else 0}, "
               f"max={max(emo_dist.values()) if emo_dist else 0})")
    if not emo_items:
        raise SystemExit("no emotion_story segments found — nothing to extract.")

    # ── Output path + run config ────────────────────────────────────────────
    out_dir = data_dir / "features" / spec_hash / safe_name(target)
    out_dir.mkdir(parents=True, exist_ok=True)
    run_config = {
        **logger.decisions, "target_model": target, "spec_hash": spec_hash,
        "generator_model": generator_used, "stories_file": str(stories_file),
        "work_dir": str(work_dir), "n_segments": len(items), "n_emotions": len(emo_dist),
        "n_neutral": len(neutral_idx), "started": stamp,
    }
    (out_dir / "run_config.json").write_text(json.dumps(run_config, indent=2))
    logger.log(f"output   → {out_dir}")

    # ── wandb ───────────────────────────────────────────────────────────────
    logger.log("\n── wandb ──")
    if args.no_wandb:
        wandb_mode = "disabled"
        logger.decision("wandb_mode", wandb_mode, "--no-wandb")
    else:
        wandb_mode = resolver.choice("wandb_mode", args.wandb_mode, "WANDB_MODE",
                                     ["online", "offline", "disabled"], "online")
    wandb_project = resolver.value("wandb_project", args.wandb_project, "WANDB_PROJECT", "emovecllm")
    wandb_entity = resolver.value("wandb_entity", args.wandb_entity, "WANDB_ENTITY", "")
    run_name = resolver.value("wandb_run_name", args.wandb_run_name, "WANDB_RUN_NAME",
                              f"extract-{safe_name(target)}-{spec_hash}-{stamp}")
    wb = Wandb(wandb_mode, wandb_project, wandb_entity, run_name, run_config, logger)

    # ── Load target model + probe shapes ────────────────────────────────────
    import torch
    from generate_dataset import detect_device
    device, vram = detect_device(logger)
    extract_resid, refeed_features, used_backend = load_target(
        target, backend, precision, device_map, device, vram, max_tokens, logger)
    probe_resid, _ = extract_resid(emo_items[0]["text"])
    n_layers, _, d_model = probe_resid.shape
    cluster_l = resolve_layer(cluster_layer, n_layers)
    cum_l = resolve_layer(cum_layer, n_layers)
    cum_layer_idx = resolve_layer_set(cum_layers, n_layers, cum_l)
    logger.log(f"resid    : (n_layers={n_layers}, seq<= {max_tokens}, d_model={d_model})")
    logger.log(f"layers   : cluster={cluster_l}  proj={cum_l}  per-step={cum_layer_idx}")
    wb.summary(n_layers=n_layers, d_model=d_model, used_backend=used_backend,
               cluster_layer=cluster_l, cum_proj_layer=cum_l)

    # ── Pick which segments get a saved per-step timeseries (spread over emotions) ──
    ts_pick = set()
    if max_ts and emo_items:
        by_emo = defaultdict(list)
        for i, it in enumerate(items):
            if it["kind"] == "emotion_story":
                by_emo[it["emotion"]].append(i)
        order, ptr = list(by_emo), 0
        while len(ts_pick) < max_ts and order:
            e = order[ptr % len(order)]
            if by_emo[e]:
                ts_pick.add(by_emo[e].pop(0))
            else:
                order.remove(e)
                continue
            ptr += 1

    def per_step_features(resid, text, layer_idx):
        if cum_method == "refeed":
            feats, toks = refeed_features(text, layer_idx)
            if skip_first and feats.shape[0] > 1:
                feats, toks = feats[1:], toks[1:]
            return feats, toks
        return resid[layer_idx].transpose(1, 0, 2), None   # (seq, n_sel, d), causal-exact

    # ── Extract ─────────────────────────────────────────────────────────────
    logger.log(f"\nextracting {len(items)} segments "
               f"({len(ts_pick)} get a per-step timeseries) …")
    X = np.zeros((len(items), n_layers, d_model), dtype=np.float32)
    n_tokens = np.zeros(len(items), dtype=np.int32)
    cum_list, cum_meta = [], []
    LOG_EVERY = max(1, len(items) // 50)
    t0 = time.time()
    for i, it in enumerate(items):
        resid, toks = extract_resid(it["text"])
        if skip_first and resid.shape[1] > 1:           # drop token-0 attention sink
            resid = resid[:, 1:, :]
            toks = toks[1:]
        n_tokens[i] = resid.shape[1]
        X[i] = pool_segment(resid, pool)
        if i in ts_pick:
            feats, toks2 = per_step_features(resid, it["text"], cum_layer_idx)
            cum_list.append(feats.astype(np.float16))
            cum_meta.append({"emotion": it["emotion"], "kind": it["kind"],
                             "job_id": it["job_id"], "topic": it["topic"],
                             "tokens": (toks2 or toks)[:feats.shape[0]]})
        if (i + 1) % LOG_EVERY == 0 or i + 1 == len(items):
            el = time.time() - t0
            sps = (i + 1) / max(el, 1e-9)
            frac = (i + 1) / len(items)
            wb.log({"segments_done": i + 1, "fraction_complete": frac,
                    "segments_per_sec": sps, "timeseries_kept": len(cum_list),
                    "eta_min": (len(items) - i - 1) / max(sps, 1e-9) / 60}, step=i + 1)
            logger.log(f"  {i+1}/{len(items)}  {sps:.1f} seg/s  "
                       f"ETA {(len(items)-i-1)/max(sps,1e-9)/60:.0f} min")
    logger.log(f"extracted {len(items)} segments in {(time.time()-t0)/60:.1f} min")

    # ── Baseline → emotion vectors → clusters (nb04 §6) ─────────────────────
    class_segs = defaultdict(list)
    for i, it in enumerate(items):
        if it["kind"] == "emotion_story" and it["emotion"]:
            class_segs[it["emotion"]].append(i)
    class_means = {e: X[idx].mean(axis=0) for e, idx in class_segs.items()}
    n_per_emotion = {e: len(idx) for e, idx in class_segs.items()}
    global_mean = X.mean(axis=0)
    neutral_mean = X[neutral_idx].mean(axis=0) if neutral_idx else None
    baseline_kinds = sorted({items[i]["kind"] for i in neutral_idx})

    mode = baseline
    if mode == "auto":
        mode = "neutral_mean" if neutral_idx else "global_mean"
    if mode in ("neutral_mean", "project_pcs") and not neutral_idx:
        logger.log("no neutral segments → falling back to global_mean baseline")
        mode = "global_mean"

    neutral_pcs = None
    if mode == "project_pcs":
        from sklearn.decomposition import PCA
        Xn = X[neutral_idx]
        neutral_pcs = []
        for L in range(n_layers):
            kk = min(baseline_pcs, max(1, Xn.shape[0] - 1))
            neutral_pcs.append(
                PCA(n_components=kk).fit(Xn[:, L, :] - Xn[:, L, :].mean(0)).components_)

    emotions, V = build_emotion_vectors(class_means, neutral_mean, global_mean, mode, neutral_pcs)
    logger.log(f"baseline : {mode}  (kinds: {baseline_kinds or 'none'})")
    logger.log(f"vectors  : {V.shape}  ({len(emotions)} emotions × {n_layers} layers × {d_model})")

    from sklearn.cluster import KMeans
    Vc = V[:, cluster_l, :]
    k_eff = int(min(k, max(2, len(emotions))))
    if len(emotions) >= 2:
        cluster_labels = KMeans(n_clusters=k_eff, n_init=10, random_state=0).fit(_unit(Vc)).labels_
    else:
        cluster_labels = np.zeros(len(emotions), dtype=int)
    logger.log(f"clusters : k={k_eff} over {len(emotions)} vectors at layer {cluster_l}")

    # ── Save (nb04 §7) ──────────────────────────────────────────────────────
    np.savez_compressed(
        out_dir / "segment_features.npz", X=X, n_tokens=n_tokens,
        emotions=np.array([it["emotion"] for it in items], dtype=object),
        kinds=np.array([it["kind"] for it in items], dtype=object),
        job_ids=np.array([it["job_id"] for it in items], dtype=object),
        topics=np.array([it["topic"] for it in items], dtype=object),
        pool=pool, target_model=target, spec_hash=spec_hash,
        n_layers=n_layers, d_model=d_model)
    np.savez_compressed(
        out_dir / "emotion_vectors.npz", vectors=V,
        emotions=np.array(emotions, dtype=object),
        class_means=np.stack([class_means[e] for e in emotions], axis=0),
        n_per_emotion=np.array([n_per_emotion[e] for e in emotions]),
        baseline_mean=(neutral_mean if neutral_mean is not None else global_mean),
        global_mean=global_mean, baseline_mode=mode,
        baseline_kinds=np.array(baseline_kinds, dtype=object),
        cluster_labels=cluster_labels, cluster_layer=cluster_l, k=k_eff,
        cum_layer=cum_l, skip_first=skip_first,
        target_model=target, spec_hash=spec_hash)
    np.savez_compressed(
        out_dir / "cumulative_timeseries.npz",
        cum=np.array(cum_list, dtype=object),
        cum_emotions=np.array([m["emotion"] for m in cum_meta], dtype=object),
        cum_kinds=np.array([m["kind"] for m in cum_meta], dtype=object),
        cum_job_ids=np.array([m["job_id"] for m in cum_meta], dtype=object),
        cum_topics=np.array([m["topic"] for m in cum_meta], dtype=object),
        cum_tokens=np.array([m["tokens"] for m in cum_meta], dtype=object),
        cum_layer_indices=np.array(cum_layer_idx),
        cum_proj_layer=cum_l, cum_method=cum_method, skip_first=skip_first,
        target_model=target, spec_hash=spec_hash)

    manifest = {
        "spec_hash": spec_hash, "target_model": target, "backend": used_backend,
        "stories_file": str(stories_file), "generator_model": generator_used,
        "n_segments": len(items), "n_emotions": len(emotions),
        "n_neutral": len(neutral_idx), "n_timeseries": len(cum_list),
        "pool": pool, "skip_first": bool(skip_first), "baseline_mode": mode,
        "baseline_kinds": baseline_kinds, "n_layers": int(n_layers), "d_model": int(d_model),
        "cluster_layer": int(cluster_l), "cum_proj_layer": int(cum_l),
        "cum_layer_indices": [int(x) for x in cum_layer_idx], "cum_method": cum_method,
        "k": int(k_eff), "demo": bool(demo), "updated": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
    }
    (out_dir / "features_manifest.json").write_text(json.dumps(manifest, indent=2))
    logger.log(f"saved    → {out_dir}")

    # ── Sanity check + wandb artifact (nb04 §8) ─────────────────────────────
    S = cosine_sim_matrix(V[:, cluster_l, :])
    np.fill_diagonal(S, -np.inf)
    nn = S.argmax(axis=1)
    agree = float(np.mean([cluster_labels[i] == cluster_labels[nn[i]]
                           for i in range(len(emotions))])) if len(emotions) else 0.0
    logger.log(f"sanity   : nearest-neighbour shares cluster {100*agree:.0f}% "
               f"(chance ~{100/max(k_eff,1):.0f}%)")

    wb.summary(n_segments=len(items), n_emotions=len(emotions), n_timeseries=len(cum_list),
               baseline_mode=mode, nn_cluster_agreement=agree, runtime_min=(time.time()-t0)/60)
    wb.log_artifact(
        f"emotion-vectors-{spec_hash}-{safe_name(target)}", "emotion-vectors",
        [out_dir / "emotion_vectors.npz", out_dir / "features_manifest.json",
         out_dir / "run_config.json"],
        metadata={"spec_hash": spec_hash, "target_model": target, "n_emotions": len(emotions),
                  "baseline_mode": mode, "nn_cluster_agreement": agree})
    wb.finish()
    logger.log("done.")
    logger.close()


if __name__ == "__main__":
    main()
